runtime: nodejs18

env_variables:
  PORT: 8080
  MONGODB_URI: mongodb+srv://jussikarhumaa:xhypyJaYOT9U9ADE@cleanbusiness.i4zibhe.mongodb.net/?retryWrites=true&w=majority&appName=Cleanbusiness
  DB_NAME: varausjarjestelma
  # Lisää tarvittaessa muut ympäristömuuttujat, esim. MONGODB_URI

handlers:
  - url: /api/.*
    script: auto

  - url: /(.*\.(js|css|png|jpg|jpeg|gif|ico|json|svg|webp|woff|woff2|ttf|eot|jsx))$
    static_files: frontend/dist/\1
    upload: frontend/dist/.*
    mime_type: application/javascript

  - url: /.*
    static_files: frontend/dist/index.html
    upload: frontend/dist/index.html