steps:
  # Buildaa Docker-image
  - name: 'Build Docker Image'
    image: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/webapp-457108/fullstack:$SHORT_SHA', '.']

  # Pushaa Docker-image Google Container Registryyn (GCR)
  - name: 'Push Docker Image to GCR'
    image: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/webapp-457108/fullstack:$SHORT_SHA']

  # Deployaa Cloud Runiin
  - name: 'Deploy to Cloud Run'
    image: 'google/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'fullstack-$SHORT_SHA' # Palvelun nimi Cloud Runissa
      - '--image'
      - 'gcr.io/webapp-457108/fullstack:$SHORT_SHA'
      - '--region'
      - 'europe-north1' # Valitse sopiva alue (Oulu lähellä)
      - '--platform'
      - 'managed'
      - '--port'
      - '8080'
      # Lisää tarvittavat ympäristömuuttujat tähän
      - '--set-env-vars'
      - 'MONGODB_URI=mongodb+srv://jussikarhumaa:xhypyJaYOT9U9ADE@cleanbusiness.i4zibhe.mongodb.net/?retryWrites=true&w=majority&appName=Cleanbusiness,DB_NAME=varausjarjestelma,SMTP_USER=api,SMTP_PASS=c9b685fc59d0a3303b95f88a0aa49a75,CONTACT_EMAIL=test@demomailtrap.co,ADMIN_EMAIL=jussikarhumaa@gmail.com,PORT=8080,NODE_ENV=development,CORS_ORIGIN=http://localhost:5173'
    waitFor: ['Push Docker Image to GCR']